//각각 type들의 형태를 변수로 관리(오타 방지 및 관리 편하게 하기 위해)

export const LOGIN_USER ="LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";

export const AUTH_USER = "AUTH_USER";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const FIND_PASSWORD = "FIND_PASSWORD";
export const FIND_ACCOUNT_FIRST = "FIND_ACCOUNT_FIRST";
export const FIND_ACCOUNT_SECOND = "FIND_ACCOUNT_SECOND";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const IMAGE_HANDLER = "IMAGE_HANDLER";
export const SUGGEST_POST = "SUGGEST_POST";
export const GET_SUGGEST_TOKEN = "GET_SUGGEST_TOKEN";
export const GET_POSTING_INFO = "GET_POSTING_INFO";
export const POSTING_COMMENT = "POSTING_COMMENT";

//전체게시글 조회
export const GET_POSTING_ALL_RANDOM = "GET_POSTING_ALL_RANDOM";
export const GET_POSTING_ALL_UPDATE = "GET_POSTING_ALL_UPDATE";
export const GET_POSTING_ALL_ENDDATE = "GET_POSTING_ALL_ENDDATE"
//카테고리별 게시글 조회
export const GET_POSTING_KIDS = "GET_POSTING_KIDS";
export const GET_POSTING_YOUNG = "GET_POSTING_YOUNG";
export const GET_POSTING_WOMAN = "GET_POSTING_WOMAN";
export const GET_POSTING_OLDS = "GET_POSTING_OLDS";
export const GET_POSTING_DISABLED = "GET_POSTING_DISABLED";
export const GET_POSTING_SOCIAL = "GET_POSTING_SOCIAL";
export const GET_POSTING_EARTH = "GET_POSTING_EARTH";
export const GET_POSTING_NEIGHBORHOOD = "GET_POSTING_NEIGHBORHOOD";
export const GET_POSTING_ANIMAL = "GET_POSTING_ANIMAL";
export const GET_POSTING_ENVIRONMENT = "GET_POSTING_ENVIRONMENT";